version: '2'
services:
  postgres:
    image: postgres
    volumes:
      - ./volumes/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db